#1. k: v #k v 之前 是空格区分
#2. 属性有层级关系，使用下一行，空两个空格
#3. 左侧对齐的代表同一层级的属性

server:
  port: 9999

spring:
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: aaa

person:
  name: devil
  age: 28
  birthday: 2005/03/15 12:30:30
  like: true
  child:
    name: huhu
    age: 8
    birthday: 2025/10/10
    text: ["abc","def"]
  dogs:
    - name: 小黑
      age: 2
    - name: 小白
      age: 3
  cats:
    c1:
      name: 小灰
      age: 4
    c2: {name: 小蓝,age: 5} #对象也可以用{}表示